spring:
  thymeleaf.cache: true
  jpa:
    hibernate:
    #TBD change this to none when database schema stable
      ddl-auto: update
      database: MYSQL
      show-sql: true
      use-new-id-generator-mappings: true
      dialect: org.hibernate.dialect.MySQL5
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/entityMgt
      username: root
      password: password
javax.xml.accessExternalSchema : all

#google.api.key=AIzaSyDYkdBkPcuYouBruy7DxSERqrunq8pjQIc
#google.api.key=AIzaSyCawS544HTlwRGkBDDjbM2mMj98VwatQRE
#google.api.key=AIzaSyAKLZ0EOkeqp_Rk9Guh1SsT1MuJM7wdFkw
#google.api.key=AIzaSyDDZZzlPmd_u9prMkaE8YMmvp6IP9KN72M
#google.api.key=AIzaSyBdtRny8HaYV4OQmOKEvRBrKH5k4nBDtQ0
google.api.key: AIzaSyC2WAbfmvicCd7eOKRzCIPS-_TfM4YUxvE