spring:
  thymeleaf.cache: true
  jpa:
    hibernate:
    #TBD change this to none when database schema stable
#      ddl-auto: update
      ddl-auto: update
      database: MYSQL
      show-sql: true
      use-new-id-generator-mappings: true
      dialect: org.hibernate.dialect.MySQL5
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/entityMgt
#      username: root
#      password: password
  data.rest.baseUri: data
  social:
      linkedin:
        app-id: 86ys6tl0fl22nn
        app-secret: XitDHnd0wMTEmGEn
javax.xml.accessExternalSchema : all



security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'
linkedin:
  client:
    clientId: 86ow2v29be48bm
    clientSecret: NsXEwpY09JtLBrHQ
    accessTokenUri: https://www.linkedin.com/oauth/v2/accessToken
    userAuthorizationUri: https://www.linkedin.com/oauth/v2/authorization
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.linkedin.com/v1/people/~?format=json

logging.level.org.springframework.web: INFO
logging.level.org.springframework.security: INFO
logging.level.org.hibernate: ERROR
#  file: cicidiHome.log


#google.api.key=AIzaSyDYkdBkPcuYouBruy7DxSERqrunq8pjQIc
#google.api.key=AIzaSyCawS544HTlwRGkBDDjbM2mMj98VwatQRE
#google.api.key=AIzaSyAKLZ0EOkeqp_Rk9Guh1SsT1MuJM7wdFkw
#google.api.key=AIzaSyDDZZzlPmd_u9prMkaE8YMmvp6IP9KN72M
#google.api.key: AIzaSyBdtRny8HaYV4OQmOKEvRBrKH5k4nBDtQ0
google.api.key: AIzaSyC2WAbfmvicCd7eOKRzCIPS-_TfM4YUxvE
---
spring:
  profiles: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/entityMgt
      username: root
      password: password
resumeConfig: /resume_config
tmpFolder: /tmp
env: dev

---
spring:
  profiles: prod
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://cicidi-home-db.clkbcosqz5bn.us-west-1.rds.amazonaws.com:3306/entityMgt
      url: jdbc:mysql://localhost:3306/entityMgt
      username: root
      password: password
resumeConfig: /resume_config
tmpFolder: /cicidi-home
env: prod